openapi: 3.0.0
info:
  title: Kaltura API
  version: 1.0.0
  description: API for retrieving Kaltura media entries and captions
servers:
  - url: https://copilot-server-test.onrender.com
paths:
  /kaltura/entries:
    get:
      summary: Get Kaltura entries
      operationId: getKalturaEntries
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        thumbnailUrl:
                          type: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Server Error
  /kaltura/captions/{entryId}:
    get:
      summary: Get captions for entry
      operationId: getKalturaCaptions
      security:
        - BearerAuth: []
      parameters:
        - name: entryId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  caption_id:
                    type: string
                  entry_id:
                    type: string
                  format:
                    type: string
                  language:
                    type: string
                  content:
                    type: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Server Error
  /magic-response:
    post:
      summary: Magic response
      operationId: getMagicResponse
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
              required:
                - question
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
        '401':
          description: Unauthorized
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer