openapi: 3.0.1
info:
  title: Hello Plugin
  version: 1.0.0
servers:
  - url: https://copilot-server-test.onrender.com
paths:
  /hello:
    get:
      summary: Say hello
      operationId: sayHello
      responses:
        '200':
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
